# Set workspace configuration

# Set the monitors names
set $firstMonitor HDMI-1
set $secondMonitor DP-1

# Define workspace variables
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# Define workspace output monitors configuration
workspace $ws1 output $firstMonitor
workspace $ws2 output $firstMonitor
workspace $ws3 output $firstMonitor
workspace $ws4 output $firstMonitor
workspace $ws5 output $firstMonitor
workspace $ws6 output $secondMonitor
workspace $ws7 output $secondMonitor
workspace $ws8 output $secondMonitor
workspace $ws9 output $secondMonitor
workspace $ws10 output $secondMonitor
